# Career Path Advisor Chatbot

## 📌 Project Goal
The goal of this project is to build an **advisor chatbot** that helps individuals make informed career decisions. The chatbot will recommend possible **career paths** based on the skills a person currently possesses and also suggest **additional skills** they can learn to expand their opportunities and transition into different fields.

## 🔍 Problem Statement
Many people have valuable skills but struggle to identify:
- The types of jobs or roles they are best suited for.
- What complementary skills they need to acquire in order to pivot into new industries or advance in their careers.

This lack of clarity often leads to underemployment or missed opportunities.

## 💡 Solution
The Career Path Advisor Chatbot will:
1. Accept a list of **current skills** from a user.
2. Map these skills to **job descriptions** in a dataset of careers.
3. Recommend relevant **job titles and career paths** that align with the user’s existing skill set.
4. Suggest **new skills to learn** that complement the current ones and enable the user to transition into other fields or improve employability.

## 📊 Dataset
The project uses a dataset of **job descriptions**, including:
- **Job Titles**
- **Required Skills**
- **Job Descriptions**

This dataset provides the foundation for matching user skills to career opportunities.

## 🔧 Methodology
- **Data Preprocessing**: Clean and structure job descriptions and skill requirements.
- **Skill Extraction & Matching**: Use NLP techniques to extract skills from text and match them to user input.
- **Recommendation System**: Suggest suitable jobs and additional skills for career advancement.
- **Chatbot Interface**: Deploy the solution as an interactive chatbot that users can engage with naturally.

## 🚀 Expected Outcome
By the end of this project, users will have a **personalized career advisor chatbot** that:
- Guides them toward roles that match their current skills.
- Provides clear advice on **what to learn next** to remain competitive and versatile in the job market.

This tool can empower individuals to take control of their career growth and explore opportunities they may not have considered otherwise.

# THE FIRST STEP START HERE.

The first step is to call up the dataset that we got from huggingface and was saved to our local computer.

In [1]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
import random
import contractions
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
import datetime
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings("ignore")

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading wordnet: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

In [3]:
# import pandas so that it can be used to read the dataset we had got from huggingface and display the first five rows.
df = pd.read_csv("Joblisting.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Joblisting.csv'

## Data Preprocessing.

In [7]:
#check if there are any duplicates in the dataset.
df.duplicated().sum()

0

In [8]:
# check for missing values
df.isna().sum()

Job Id                 0
Experience             0
Qualifications         0
Salary Range           0
location               0
Country                0
latitude               0
longitude              0
Work Type              0
Company Size           0
Job Posting Date       0
Preference             0
Contact Person         0
Contact                0
Job Title              0
Role                   0
Job Portal             0
Job Description        0
Benefits               0
skills                 0
Responsibilities       0
Company                0
Company Profile     5478
dtype: int64

In [9]:
df1 = df[["Job Title","skills","Experience"]]
df1

,Job Title,skills,Experience
0,Digital Marketing Specialist,"Social media platforms (e.g., Facebook, Twitte...",5 to 15 Years
1,Web Developer,"HTML, CSS, JavaScript Frontend frameworks (e.g...",2 to 12 Years
2,Operations Manager,Quality control processes and methodologies St...,0 to 12 Years
3,Network Engineer,Wireless network design and architecture Wi-Fi...,4 to 11 Years
4,Event Manager,Event planning Conference logistics Budget man...,1 to 12 Years
...,...,...,...
1615935,Mechanical Engineer,"Mechanical engineering CAD software (e.g., Sol...",0 to 12 Years
1615936,IT Manager,Strategic IT planning Leadership and managemen...,2 to 14 Years
1615937,Mechanical Engineer,"Mechanical engineering CAD software (e.g., Sol...",4 to 15 Years
1615938,HR Coordinator,Training program coordination Training materia...,5 to 15 Years
1615939,Event Planner,Wedding planning Venue selection Catering and ...,1 to 11 Years

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615940 entries, 0 to 1615939
Data columns (total 3 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Job Title   1615940 non-null  object
 1   skills      1615940 non-null  object
 2   Experience  1615940 non-null  object
dtypes: object(3)
memory usage: 37.0+ MB

In [11]:
df1.rename(columns={
    'Job Title': 'Job_Title',
    'skills': 'Skills',
    'Experience': 'Experience'
}, inplace=True)
df1.head()

,Job_Title,Skills,Experience
0,Digital Marketing Specialist,"Social media platforms (e.g., Facebook, Twitte...",5 to 15 Years
1,Web Developer,"HTML, CSS, JavaScript Frontend frameworks (e.g...",2 to 12 Years
2,Operations Manager,Quality control processes and methodologies St...,0 to 12 Years
3,Network Engineer,Wireless network design and architecture Wi-Fi...,4 to 11 Years
4,Event Manager,Event planning Conference logistics Budget man...,1 to 12 Years

In [12]:
# Inspecting the unque classes of Job Title in the dataset for possible cleaning and normalization
df1.Job_Title.unique()

array(['Digital Marketing Specialist', 'Web Developer',
       'Operations Manager', 'Network Engineer', 'Event Manager',
       'Software Tester', 'Teacher', 'UX/UI Designer', 'Wedding Planner',
       'QA Analyst', 'Litigation Attorney', 'Mechanical Engineer',
       'Network Administrator', 'Account Manager', 'Brand Manager',
       'Social Worker', 'Social Media Coordinator',
       'Email Marketing Specialist', 'HR Generalist', 'Legal Assistant',
       'Nurse Practitioner', 'Account Director', 'Software Engineer',
       'Purchasing Agent', 'Sales Consultant', 'Civil Engineer',
       'Network Security Specialist', 'UI Developer', 'Financial Planner',
       'Event Planner', 'Psychologist', 'Electrical Designer',
       'Data Analyst', 'Technical Writer', 'Tax Consultant',
       'Account Executive', 'Systems Administrator',
       'Database Administrator', 'Research Analyst', 'Data Entry Clerk',
       'Registered Nurse', 'Investment Analyst', 'Speech Therapist',
       'Sales Manager', 'Landscape Architect', 'Key Account Manager',
       'UX Researcher', 'Investment Banker', 'IT Support Specialist',
       'Art Director', 'Software Developer', 'Project Manager',
       'Customer Service Manager', 'Procurement Manager',
       'Substance Abuse Counselor', 'Supply Chain Analyst',
       'Data Engineer', 'Accountant', 'Sales Representative',
       'Environmental Consultant', 'Electrical Engineer',
       'Systems Engineer', 'Art Teacher', 'Human Resources Manager',
       'Inventory Analyst', 'Legal Counsel', 'Database Developer',
       'Procurement Specialist', 'Systems Analyst', 'Copywriter',
       'Content Writer', 'HR Coordinator', 'Business Development Manager',
       'Java Developer', 'Supply Chain Manager', 'Event Coordinator',
       'Family Nurse Practitioner', 'Front-End Engineer',
       'Customer Success Manager', 'Procurement Coordinator',
       'Urban Planner', 'Architectural Designer', 'Financial Analyst',
       'Environmental Engineer', 'Back-End Developer',
       'Structural Engineer', 'Market Research Analyst',
       'Customer Service Representative', 'Customer Support Specialist',
       'Business Analyst', 'Social Media Manager', 'Family Lawyer',
       'Chemical Analyst', 'Network Technician', 'Interior Designer',
       'Software Architect', 'Nurse Manager', 'Veterinarian',
       'Process Engineer', 'IT Manager', 'Quality Assurance Analyst',
       'Pharmaceutical Sales Representative', 'Office Manager',
       'Architect', 'Physician Assistant', 'Marketing Director',
       'Front-End Developer', 'Research Scientist', 'Executive Assistant',
       'HR Manager', 'Marketing Manager', 'Public Relations Specialist',
       'Financial Controller', 'Investment Advisor', 'Aerospace Engineer',
       'Marketing Analyst', 'Paralegal', 'Landscape Designer',
       'Web Designer', 'Occupational Therapist', 'Legal Advisor',
       'Marketing Coordinator', 'Dental Hygienist', 'SEM Specialist',
       'SEO Specialist', 'Pediatrician', 'QA Engineer', 'Data Scientist',
       'Financial Advisor', 'Personal Assistant', 'SEO Analyst',
       'Network Analyst', 'Mechanical Designer', 'Marketing Specialist',
       'Graphic Designer', 'Finance Manager', 'Physical Therapist',
       'Product Designer', 'Administrative Assistant', 'Brand Ambassador',
       'Project Coordinator', 'Product Manager', 'IT Administrator',
       'Sales Associate', 'Chemical Engineer', 'Legal Secretary',
       'Market Analyst'], dtype=object)

In [13]:
# Inspecting the unque classes of Skills in the dataset for possible cleaning and normalization
df1.Skills.unique()

array(['Social media platforms (e.g., Facebook, Twitter, Instagram) Content creation and scheduling Social media analytics and insights Community engagement Paid social advertising',
       'HTML, CSS, JavaScript Frontend frameworks (e.g., React, Angular) User experience (UX)',
       'Quality control processes and methodologies Statistical process control (SPC) Root cause analysis and corrective action Quality management systems (e.g., ISO 9001) Compliance and regulatory knowledge',
       'Wireless network design and architecture Wi-Fi standards and protocols RF (Radio Frequency) planning and optimization Wireless security protocols Troubleshooting wireless network issues',
       'Event planning Conference logistics Budget management Vendor coordination Marketing and promotion Client relations',
       'Quality assurance processes Testing methodologies (e.g., manual, automated) Bug tracking and reporting Test case development Regression testing',
       'Teaching pedagogy Classroom management Curriculum development Student assessment Differentiated instruction',
       'UI design principles and best practices Graphic design tools (e.g., Adobe Photoshop, Illustrator) Typography and color theory Visual design and layout Responsive design',
       'Interaction design principles User behavior and psychology Wireframing and prototyping tools Animation and micro-interaction design Collaborative design processes',
       'Wedding planning Vendor coordination Event management',
       'Performance testing Load testing Stress testing Test scenarios Performance monitoring Benchmarking Performance analysis',
       'Family law Divorce proceedings Child custody Mediation Legal counseling Court representation',
       'Mechanical engineering CAD software (e.g., SolidWorks, AutoCAD) Finite element analysis Product development Prototyping',
       'Network security protocols Intrusion detection and prevention Security incident response Firewall administration Vulnerability assessment Security policies and procedures Log analysis Ethical hacking Problem-solving Communication skills Attention to detail',
       'Account management Sales strategy Negotiation and closing skills',
       'Product branding and marketing Product lifecycle management Cross-functional team collaboration Product launch planning Market segmentation and targeting',
       'School social work principles Student assessment and intervention Special education laws Individualized education plans (IEPs) Crisis management Collaboration with educators Family engagement Advocacy Empathy and communication Documentation Cultural competence Licensing and certification',
       'Content creation (e.g., writing, editing, graphic design, video production) Content marketing Social media management SEO optimization Creative storytelling Audience engagement Analytics and reporting Adaptability Communication skills Creativity',
       'Email deliverability best practices Spam filter testing List hygiene Blacklist monitoring Email authentication (e.g., SPF, DKIM) Deliverability metrics analysis Troubleshooting deliverability issues Communication skills Data analysis Attention to detail',
       'Human resources Recruitment Employee onboarding HRIS (HR Information Systems) Record keeping Communication skills',
       'Legal administrative tasks Document management Calendar and docketing Transcription File organization Communication with clients and courts Knowledge of legal terminology Attention to detail Multitasking Computer skills (e.g., MS Office)',
       'Family medicine Health assessment Pediatric care Chronic disease management Patient education',
       'Account management Client relations Marketing strategies Campaign optimization Data analysis Communication skills',
       'Proficiency in one or more backend programming languages (e.g., Java, Python, Node.js, Ruby) API development Database management (SQL or NoSQL) Server management and deployment Security best practices Knowledge of web frameworks (e.g., Express, Django)',
       'Supply chain logistics Inventory management Communication skills Problem-solving Vendor coordination',
       'B2B sales Business-to-business sales strategies Lead generation Sales negotiations Client relationship building Market research',
       'Structural engineering principles Structural analysis and design software (e.g., AutoCAD, SAP2000) Building codes and standards Project management Structural integrity assessment',
       'SOC operations Security incident response Threat detection Log analysis Security tools (e.g., IDS/IPS) Security alerts triage',
       'Front-end web development HTML, CSS, JavaScript Responsive design Web performance optimization Cross-browser compatibility',
       'Tax planning strategies Tax law knowledge Financial analysis Retirement planning Estate planning Client relationship management Tax optimization Communication skills Attention to detail Tax software proficiency Regulatory compliance',
       'Event planning Vendor coordination Budget management Marketing and promotion Logistics',
       'Clinical psychology Counseling skills Assessment tools Diagnostic skills Empathy and listening skills',
       'Electrical engineering Circuit design Electronics AutoCAD proficiency Problem-solving',
       'Lighting design Architectural lighting Lighting software proficiency Creative lighting concepts Technical knowledge',
       'Data analysis and visualization tools (e.g., Tableau, Power BI) SQL and database querying Business intelligence concepts Data modeling and reporting Strong analytical and problem-solving skills Data-driven decision-making',
       'Writing skills Content creation SEO knowledge Research skills Grammar and proofreading',
       'Tax law knowledge Individual tax planning Tax return preparation Tax deductions and credits Tax compliance IRS regulations Client relationship management Communication skills Attention to detail Tax software proficiency',
       'Test automation tools (e.g., Selenium, Appium) Scripting languages (e.g., Python, Java) Test framework development Continuous integration tools Test data management',
       'Sales strategies and tactics Account management Relationship building Sales forecasting Industry and product knowledge',
       'Technical troubleshooting Hardware and software support Customer service Problem-solving Communication',
       'Database design and development SQL and database querying Data modeling Programming languages (e.g., Java, Python) Data security and privacy regulations knowledge',
       'Social science research methods Qualitative and quantitative data analysis Survey design and implementation Ethnographic research Interviewing skills Research ethics Statistical software (e.g., Stata, NVivo) Report writing Communication skills Critical thinking Empathy',
       'Records management Data entry and retrieval Attention to detail',
       'Nursing care Patient assessment Medical knowledge',
       'International tax law knowledge Transfer pricing Cross-border tax planning Tax treaties and agreements Foreign tax credits International tax compliance Transfer pricing documentation Multinational tax strategies Client relationship management Communication skills Tax software proficiency',
       'Risk assessment Data analysis Financial modeling Risk management tools Regulatory compliance knowledge',
       'Speech pathology Articulation therapy Language disorders Speech assessment Therapy planning Communication skills',
       'Sales strategy development Territory management Sales team leadership',
       'Counseling techniques Psychotherapy Mental health assessment Treatment planning Crisis intervention Ethical standards Empathy and active listening Cultural competence Documentation Communication skills Self-care Licensing and certification',
       'Urban design and planning Zoning regulations GIS and mapping tools',
       'Account management Client relationship Sales strategy Business development Negotiation skills',
       'User research methods Usability testing Data analysis and interpretation',
       'Financial analysis Data analysis Financial modeling',
       'Desktop hardware and software troubleshooting Operating system expertise (e.g., Windows, macOS) Remote desktop support Hardware and software upgrades Customer service skills',
       'Art history and knowledge Art curation and exhibition planning Collections management Art market trends Cultural awareness',
       'Mobile app development languages (e.g., Java, Swift, Kotlin) Cross-platform development (e.g., React Native, Flutter) Mobile app design principles APIs and web services integration Debugging and troubleshooting',
       'Agile methodologies Scrum or Kanban Team collaboration Agile tools (e.g., Jira)',
       'Quality assurance Quality control Process improvement Audit procedures Compliance standards Root cause analysis',
       'Procurement processes Vendor assessment Contract negotiation Purchase order management Spend analysis Market research Supplier relationship management Data analysis Problem-solving Attention to detail Communication skills Financial acumen',
       'Family counseling Marriage and family therapy Conflict resolution skills',
       'Supply chain analysis Data analytics Inventory management Transportation planning Problem-solving',
       'Data architecture design Database management systems Data modeling',
       'Document management Recordkeeping Attention to detail Data entry Organizational skills',
       'Financial reporting Accounting software (e.g., QuickBooks) Auditing GAAP knowledge',
       'Sales prospecting and lead generation Sales presentation and communication CRM software (e.g., Salesforce) Sales negotiation and closing techniques Product knowledge Relationship building',
       'Inventory control Demand forecasting Supply chain management Data analysis Warehouse management',
       'Test automation Test framework development Continuous integration Scripting languages (e.g., Python) Test reporting Code review',
       'Sustainability consulting Sustainability assessments Sustainable practices Green building standards Environmental policies Client communication',
       'Electronics design PCB layout Embedded systems Circuit analysis Troubleshooting',
       'Systems integration Integration architecture Data mapping Middleware technologies API integration System testing Troubleshooting',
       'Brand strategy development Market research and analysis Competitive analysis Brand positioning and messaging Creative direction and collaboration',
       'Acute care nursing Emergency medicine Critical care Diagnostic tests Treatment planning',
       'Litigation Legal research Courtroom representation Case preparation Client counseling Legal writing',
       'Network security protocols and technologies Firewalls and intrusion detection systems Vulnerability assessment and penetration testing Security policy development and enforcement Incident response and recovery',
       'Research methodology Data analysis Psychological studies Writing research reports Critical thinking',
       'Art education curriculum Program development Teacher training Communication skills Artistic expertise',
       'Talent sourcing Interviewing Onboarding Recruitment strategies HR software',
       'Inventory management Stock control Demand forecasting Inventory tracking systems Supply chain coordination Problem-solving skills',
       'Corporate law and regulations Contract drafting and negotiation Legal research and analysis Risk management Excellent communication and negotiation skills',
       'SQL (Structured Query Language) Database design Query optimization Data modeling Database maintenance Problem-solving skills',
       'Procurement strategies Supplier management Negotiation Cost analysis Supply chain management',
       'IT systems analysis Troubleshooting IT support and documentation',
       'Key account management Sales strategy development Negotiation and closing skills Relationship building Industry and market knowledge',
       'Creative writing Copywriting Advertising copy Content creation Brand storytelling Marketing campaigns Proofreading and editing',
       'Search engine algorithms and ranking factors Keyword research and analysis On-page and off-page SEO optimization SEO tools (e.g., Google Analytics, SEMrush) SEO content strategy',
       'Sales strategy and planning Account management Customer relationship management Solution selling Sales forecasting Contract negotiation Sales metrics and reporting',
       'Construction management Budgeting Contract negotiation Safety regulations',
       'Instructional design eLearning tools Curriculum development Multimedia design Learning theory knowledge',
       'Content strategy Content planning SEO optimization Content marketing Analytics',
       'Training program coordination Training material development Learning management systems',
       'Recruitment process Candidate screening Applicant tracking systems Communication',
       'Partnership development Negotiation and collaboration Business development',
       'Backend development RESTful APIs Database integration Java EE (Enterprise Edition) Performance optimization Version control (e.g., Git)',
       'Sales leadership Team management Sales strategy and planning',
       'Pediatric speech therapy Speech-language assessment Individualized treatment plans Child development Communication skills',
       'Big data technologies (Hadoop, Spark, etc.) Data processing and analysis Distributed computing',
       'NoSQL databases (e.g., MongoDB, Cassandra) Data modeling Data migration Performance tuning Scalability Distributed systems',
       'Demand forecasting Inventory management Data analysis Sales and operations planning (S&OP) ERP software proficiency',
       'Wedding design concepts Decor selection and arrangement Creative flair',
       'Event planning and coordination Budget management Vendor negotiation Venue selection and management Timeline and logistics planning Marketing and promotion Risk management Client communication Creativity Problem-solving Attention to detail',
       'Investment management Financial analysis Risk assessment Asset allocation Portfolio optimization',
       'Geriatric healthcare Geriatric assessment Geriatric treatment Elderly patient care Geriatric pharmacology',
       'JavaScript programming Frontend development Frontend frameworks (e.g., React, Angular) DOM manipulation AJAX Debugging and troubleshooting',
       'Account management Customer relationship management Sales and negotiation Business development Client needs analysis',
       'Procurement Supplier management Negotiation Supply chain management Inventory control Vendor relations',
       'Transportation planning Traffic engineering GIS proficiency Public transportation Project management',
       'Adult speech therapy Speech-language assessment Rehabilitation techniques Swallowing disorders Communication skills',
       'Employee benefits administration Benefits compliance HRIS Benefits communication',
       'Interior design Space planning Color theory Material selection CAD software (e.g., SketchUp) Client collaboration Budget management',
       'Financial analysis Investment evaluation Portfolio management Data analysis',
       'Email marketing strategies Email marketing platforms (e.g., MailChimp, HubSpot) Audience segmentation A/B testing Campaign analytics Copywriting HTML/CSS for email Marketing automation Communication skills Data analysis Attention to detail',
       'Sustainability practices Environmental management systems Green certifications',
       'Server-side programming languages (e.g., Java, Python) Database management API development',
       'System administration Server maintenance Active Directory Backup and recovery Cloud computing (e.g., AWS, Azure) Troubleshooting IT security best practices Collaboration Problem-solving Attention to detail Communication skills Technical knowledge',
       'Engineering design CAD software proficiency Problem-solving Technical knowledge Communication skills',
       'Market research coordination Survey design and administration Data analysis',
       'Customer service Call center operations Problem-solving skills',
       'Customer relationship management Onboarding and training Customer feedback analysis Retention strategies Cross-selling and upselling Strong communication and empathy Customer advocacy',
       'Environmental design principles Sustainability concepts CAD and design software',
       'Business process analysis Requirement gathering Data analysis Communication skills',
       'Social media analytics tools (e.g., Google Analytics, Facebook Insights) Data analysis and reporting Social media ROI measurement Competitive analysis Trend identification',
       'Child custody law Family law Legal advocacy Negotiation Court representation Legal research Client counseling Case preparation',
       'Machine learning algorithms and libraries (e.g., scikit-learn, TensorFlow, PyTorch) Statistical analysis and modeling Data preprocessing and cleaning Big data technologies (e.g., Hadoop, Spark) Data visualization Strong programming skills (Python, R)',
       'Clinical nursing specialization (e.g., critical care, oncology) Advanced nursing skills Patient education',
       'Quality control Quality assurance QC testing methods Compliance standards Root cause analysis Documentation Statistical analysis',
       'Electrical engineering Power system analysis Renewable energy systems Control systems Safety regulations',
       'Network security Cybersecurity Intrusion detection Security analysis Firewall management',
       'Commercial interior design Workplace ergonomics Building codes and regulations knowledge Sustainable design principles AutoCAD and Revit proficiency',
       'Addiction counseling techniques Substance abuse treatment Counseling ethics',
       'Cloud computing platforms (AWS, Azure, etc.) Cloud security Containerization (Docker, Kubernetes)',
       'Data analysis Data modeling Data visualization SQL Data tools (e.g., Tableau)',
       'Nursing management Patient care coordination Staff supervision Compliance with healthcare regulations Quality improvement Leadership skills',
       'Veterinary medicine Small animal care and surgery Animal diagnostics Preventive medicine Client communication Surgical skills Radiology Anesthesia Laboratory diagnostics Compassion and empathy Problem-solving Attention to detail',
       'Chemical engineering Process design Chemical reactions Safety protocols Laboratory techniques Problem-solving skills',
       'Market research methodologies Data collection and analysis Consumer behavior analysis Competitor analysis Survey design and analysis Statistical analysis software (e.g., SPSS, SAS) Data visualization Trend analysis Report writing Communication skills Attention to detail',
       'Network administration System administration Virtualization technologies (e.g., VMware, Hyper-V) Storage management IT security Disaster recovery planning Capacity planning Monitoring and troubleshooting Cloud infrastructure (e.g., AWS, Azure) Vendor management',
       'Test planning and strategy Test case design and execution Defect reporting and tracking Test automation tools (e.g., Selenium, Appium) Regression testing',
       'Project management Team leadership Risk management Budgeting Communication skills',
       'Client relationship management Customer service Communication skills',
       'Server-side programming (e.g., Node.js, Python) Database management (e.g., SQL, MongoDB)',
       'Medical product knowledge Understanding of healthcare regulations Relationship building with healthcare professionals Sales forecasting and planning Medical sales techniques',

In [14]:
# Inspecting the unque classes of experience in the dataset for possible cleaning and normalization
df1.Experience.unique()

array(['5 to 15 Years', '2 to 12 Years', '0 to 12 Years', '4 to 11 Years',
       '1 to 12 Years', '4 to 12 Years', '3 to 15 Years', '2 to 8 Years',
       '2 to 9 Years', '1 to 10 Years', '3 to 10 Years', '1 to 8 Years',
       '1 to 9 Years', '5 to 14 Years', '0 to 11 Years', '3 to 12 Years',
       '5 to 9 Years', '0 to 15 Years', '0 to 10 Years', '2 to 14 Years',
       '3 to 9 Years', '4 to 15 Years', '2 to 10 Years', '4 to 8 Years',
       '3 to 8 Years', '1 to 14 Years', '1 to 13 Years', '0 to 8 Years',
       '5 to 10 Years', '2 to 13 Years', '4 to 9 Years', '1 to 15 Years',
       '4 to 10 Years', '5 to 12 Years', '0 to 13 Years', '4 to 14 Years',
       '1 to 11 Years', '4 to 13 Years', '0 to 9 Years', '5 to 8 Years',
       '2 to 15 Years', '5 to 13 Years', '5 to 11 Years', '0 to 14 Years',
       '3 to 13 Years', '2 to 11 Years', '3 to 11 Years', '3 to 14 Years'],
      dtype=object)

In [15]:
#Cleaning & Normalizing Columns
def clean_column(text):
    text = str(text).lower()  # convert text to lowercase
    text = re.sub(r'[^a-z\s/]', '', text)  # remove punctuation except slashes
    text = re.sub(r'\s+', ' ', text).strip()  # remove extra spaces
    text = re.sub(r'\(.*?\)', '', text)  # remove parentheses and contents
    text = re.sub(r'[^a-z,\s]', '', text)  # remove special characters except commas
    return text

df1['Job_Title'] = df1['Job_Title'].apply(clean_column)
df1['Skills'] = df1['Skills'].apply(clean_column)

In [34]:
# dropping the experience column
df1.drop(columns=['Experience'], inplace=True)

In [36]:
df1.head()

,Job_Title,Skills,Min_Experience,Max_experience
0,digital marketing specialist,social media platforms eg facebook twitter ins...,5,15
1,web developer,html css javascript frontend frameworks eg rea...,2,12
2,operations manager,quality control processes and methodologies st...,0,12
3,network engineer,wireless network design and architecture wifi ...,4,11
4,event manager,event planning conference logistics budget man...,1,12

In [38]:
# Text preprocessing (stopwords, lemmatization)
def text_preprocessing(text):
    # Convert to lowercase
    text = str(text).lower()

    # Tokenize text into individual words
    tokens = word_tokenize(text)

    # Initialize lemmatizer
    lemmatizer = WordNetLemmatizer()

    # Load English stopwords
    stop_words = set(stopwords.words('english'))

    # Lemmatize each token (reduce word to base/dictionary form)
    # Skip words that are stopwords
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens if token not in stop_words]

    # Join the cleaned tokens back into a single string
    clean_text = " ".join(lemmatized_tokens)

    # Return final cleaned text
    return clean_text

In [40]:
df1['Job_Title_Clean'] = df1['Job_Title'].apply(text_preprocessing)
df1['Skills_Clean'] = df1['Skills'].apply(text_preprocessing)

In [44]:
# dropping the min/maxexperience column
df1.drop(columns=['Min_Experience', 'Max_experience'], inplace=True)

In [46]:
df1.head()

,Job_Title,Skills,Job_Title_Clean,Skills_Clean
0,digital marketing specialist,social media platforms eg facebook twitter ins...,digital marketing specialist,social medium platform eg facebook twitter ins...
1,web developer,html css javascript frontend frameworks eg rea...,web developer,html cs javascript frontend framework eg react...
2,operations manager,quality control processes and methodologies st...,operation manager,quality control process methodology statistica...
3,network engineer,wireless network design and architecture wifi ...,network engineer,wireless network design architecture wifi stan...
4,event manager,event planning conference logistics budget man...,event manager,event planning conference logistics budget man...

In [48]:
# Save the cleaned DataFrame to a CSV file without the index column
df1.to_csv('Joblisting_2.csv', index=False)

In [56]:
df2 = pd.read_csv('Joblisting_2.csv')
df2.head()

,Job_Title,Skills,Job_Title_Clean,Skills_Clean
0,digital marketing specialist,social media platforms eg facebook twitter ins...,digital marketing specialist,social medium platform eg facebook twitter ins...
1,web developer,html css javascript frontend frameworks eg rea...,web developer,html cs javascript frontend framework eg react...
2,operations manager,quality control processes and methodologies st...,operation manager,quality control process methodology statistica...
3,network engineer,wireless network design and architecture wifi ...,network engineer,wireless network design architecture wifi stan...
4,event manager,event planning conference logistics budget man...,event manager,event planning conference logistics budget man...

In [58]:
# Creating word count columns for job title and skills
df2['Job_Title_Word_Count'], df2['Skills_Word_Count'] = (
    df2['Job_Title_Clean'].apply(lambda x: len(str(x).split())),
    df2['Skills_Clean'].apply(lambda x: len(str(x).split()))
)

In [60]:
df2.head()

,Job_Title,Skills,Job_Title_Clean,Skills_Clean,Job_Title_Word_Count,Skills_Word_Count
0,digital marketing specialist,social media platforms eg facebook twitter ins...,digital marketing specialist,social medium platform eg facebook twitter ins...,3,19
1,web developer,html css javascript frontend frameworks eg rea...,web developer,html cs javascript frontend framework eg react...,2,11
2,operations manager,quality control processes and methodologies st...,operation manager,quality control process methodology statistica...,2,21
3,network engineer,wireless network design and architecture wifi ...,network engineer,wireless network design architecture wifi stan...,2,19
4,event manager,event planning conference logistics budget man...,event manager,event planning conference logistics budget man...,2,12

In [135]:
# Initializing the vectorizers
job_title_vectorizer = TfidfVectorizer(stop_words='english')
skills_vectorizer = TfidfVectorizer(stop_words='english')

# Fit and transform dataset text
job_title_tfidf = job_title_vectorizer.fit_transform(df2['Job_Title_Clean'])
skills_tfidf = skills_vectorizer.fit_transform(df2['Skills_Clean'])

# Example for user input (convert to same TF-IDF space)
user_job_input = input("Enter desired job title: ")   # example user query
user_skills_input = input("Enter your skills: ")  # example user query

user_job_tfidf = job_title_vectorizer.transform([user_job_input])
user_skills_tfidf = skills_vectorizer.transform([user_skills_input])

Enter desired job title:  Banking
Enter your skills:  accounting, book-keeping

In [137]:
from sklearn.metrics.pairwise import cosine_similarity

In [139]:
# Job title similarity
job_similarities = cosine_similarity(user_job_tfidf, job_title_tfidf).flatten()

# Skills similarity
skills_similarities = cosine_similarity(user_skills_tfidf, skills_tfidf).flatten()

# Combine both similarities (weighted average, you can adjust weights)
combined_similarity = (0.5 * job_similarities) + (0.5 * skills_similarities)

In [147]:
# Get top 3 job matches
top_indices = combined_similarity.argsort()[::-1][:3]

results = df2.iloc[top_indices][['Job_Title_Clean', 'Skills_Clean']]
results['Similarity_Score'] = combined_similarity[top_indices]


# Overlapping Skills
# Convert user skills to a set of tokens
user_skills_set = set(user_skills_input.lower().replace(",", " ").split())

# Function to extract overlapping skills
def get_overlap(job_skills):
    job_skills_set = set(job_skills.lower().split())
    return list(user_skills_set & job_skills_set)  # intersection

# Apply overlap detection
results['Overlapping_Skills'] = results['Skills_Clean'].apply(get_overlap)

# Final display
results = results[['Job_Title_Clean', 'Skills_Clean', 'Overlapping_Skills', 'Similarity_Score']]
results

,Job_Title_Clean,Skills_Clean,Overlapping_Skills,Similarity_Score
209651,financial controller,accounting financial reporting financial audit...,[accounting],0.211225
1163888,financial controller,accounting financial reporting financial audit...,[accounting],0.211225
488446,financial controller,accounting financial reporting financial audit...,[accounting],0.211225

In [159]:
# Career Advice Section

# Function to extract missing skills
def get_missing(job_skills):
    job_skills_set = set(job_skills.lower().split())
    return list(job_skills_set - user_skills_set)

# Generate career advice for the top job matches
career_advice = []
for i in top_indices:
    job_title = df2.loc[i, 'Job_Title_Clean']
    job_skills = df2.loc[i, 'Skills_Clean']
    
    overlapping = get_overlap(job_skills)
    missing = get_missing(job_skills)
    
    advice = {
        "Job Title": job_title,
        "Required Skills": job_skills,
        "Your Matching Skills": overlapping,
        "Suggested Skills to Learn": missing,
        "Career Advice":f"Consider learning skills in {missing} to increase your chances."
    }
    career_advice.append(advice)

career_advice_df_2 = pd.DataFrame(career_advice)
career_advice_df_2

,Job Title,Required Skills,Your Matching Skills,Suggested Skills to Learn,Career Advice
0,financial controller,accounting financial reporting financial audit...,[accounting],"[gaap, audit, accepted, reporting, principle, ...","Consider learning skills in ['gaap', 'audit', ..."
1,financial controller,accounting financial reporting financial audit...,[accounting],"[gaap, audit, accepted, reporting, principle, ...","Consider learning skills in ['gaap', 'audit', ..."
2,financial controller,accounting financial reporting financial audit...,[accounting],"[gaap, audit, accepted, reporting, principle, ...","Consider learning skills in ['gaap', 'audit', ..."